streams:
  - name: show-hn
    feed: showstories
    search_tag: show_hn
    max_items: 30
    comments: 12
    comment_story_limit: 12

  - name: ask-hn
    feed: askstories
    search_tag: ask_hn
    max_items: 30
    comments: 12
    comment_story_limit: 12
